name: 🚀 Publish release
run-name: ${{ inputs.bumpVersion == 'none' && 'Re-try making a new release' || format('Release a new {0} version', inputs.bumpVersion) }}

on:
  workflow_dispatch:
    inputs:
      bumpVersion:
        type: choice
        description: Select version to bump
        default: none
        options:
          - none
          - patch
          - minor
          - major
          - prerelease

jobs:
  release:
    name: Release a new version
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
      - name: Print all inputs and global env variables
        id: input-and-env
        run: |
          echo "Inputs:"
          echo "${{ toJSON(github.event.inputs) }}"

          echo "Env:"
          echo "${{ toJSON(env) }}"

      - name: Check out Git repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Git config
        id: git-config
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'bot@github.actions.com'

      - name: Set up Node.js 🟢
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          registry-url: 'https://npm.pkg.github.com'
          scope: '@holepunchto'

      - name: Install dependencies
        timeout-minutes: 5
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci

      - name: Update version
        if: ${{ inputs.bumpVersion != 'none' }}
        run: |
          npm version ${{ inputs.bumpVersion }}
          git push --follow-tags

      - name: Publish a npm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(npm pkg get version | tr -d \")
          if [[ "$version" == *-* ]]; then
            npm publish --tag prerelease
          else
            npm publish
          fi

      - name: Publish Github Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(npm pkg get version | tr -d \")
          gh release create "v$version" --generate-notes
